### ISSUE TITLE
Module stuck in loading

### ISSUE THREAD

**Issue by mrpicasso** [fewieden/MMM-NFL#31] opened 2020-05-16 07:53 UTC
![image](https://user-images.githubusercontent.com/47733304/82114093-298bd900-9720-11ea-9844-f4daa96322c5.png)

I noticed this in the terminal: [2020-05-16 02:44:32.106] [LOG]    Error getting NFL scores 404
Not sure why this is happening. Module was displaying the schedule without any issues when first installing it

**Comment by fewieden** [comment] 2020-05-18 17:20
The API seems to be not available. But it could also be a similar behavior than https://github.com/fewieden/MMM-NFL/issues/18

**Comment by zachgregori22** [comment] 2020-07-13 05:23
[2020-07-13 01:11:12.283] [LOG]    Error getting NFL scores 404

I have the same problem the urls go to 404 page
http://www.nfl.com/liveupdate/scorestrip/postseason/ss.xml

**Comment by fewieden** [comment] 2020-08-06 16:18
@zachgregori22 the NFL has shut down the API again. I'm open to suggestions for alternatives.

**Comment by alacercogitatus** [comment] 2020-09-11 14:20
Per https://github.com/fewieden/MMM-NFL/pull/32 I've fixed the url. It is now operational again on my instance.

**Comment by fewieden** [comment] 2020-09-16 06:25
@alacercogitatus @zachgregori22 @mrpicasso thanks to @alacercogitatus the issue is fixed now. Please pull the newest version from the master branch and run npm install

**Closed** 2022-01-22 07:47 UTC
Labels: help wanted
